name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Save Docker Images
        run: docker pull --platform amd64 istio/examples-bookinfo-details-v1:1.17.0;docker pull --platform amd64 istio/examples-bookinfo-ratings-v1:1.17.0;docker pull --platform amd64 istio/examples-bookinfo-reviews-v1:1.17.0;docker pull --platform amd64 istio/examples-bookinfo-reviews-v2:1.17.0;docker pull --platform amd64 istio/examples-bookinfo-reviews-v3:1.17.0;docker pull --platform amd64 istio/examples-bookinfo-productpage-v1:1.17.0;docker images;docker save -o calico-images-3.27.3-amd64.tar.gz istio/examples-bookinfo-details-v1:1.17.0 istio/examples-bookinfo-ratings-v1:1.17.0 istio/examples-bookinfo-reviews-v1:1.17.0 istio/examples-bookinfo-reviews-v2:1.17.0 istio/examples-bookinfo-reviews-v3:1.17.0 istio/examples-bookinfo-productpage-v1:1.17.0
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: calico-images-3.27.3-amd64.tar.gz
          tag_name: 1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
