name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Save Docker Images
        run: echo "FROM --platform=amd64 calico/kube-controllers:v3.27.3" > Dockerfile;echo 'ENTRYPOINT ["/test"]' >> Dockerfile;docker build --platform=amd64 test/kube-controllers:v3.27.3 .;echo "FROM --platform=amd64 calico/cni:v3.27.3" > Dockerfile;echo 'ENTRYPOINT ["/test"]' >> Dockerfile;docker build --platform=amd64 test/cni:v3.27.3 .;echo "FROM --platform=amd64 calico/node:v3.27.3" > Dockerfile;echo 'ENTRYPOINT ["/test"]' >> Dockerfile;docker build --platform=amd64 test/node:v3.27.3 .;docker save -o calico-amd64.tar.gz calico/kube-controllers:v3.27.3 calico/cni:v3.27.3 calico/node:v3.27.3
      - name: Release
        uses: shoothzj/latest-release-action@v1
        with:
          files: images-pull-coredns-all.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
