name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Save Docker Images
        run: docker pull --platform amd64 istio/pilot:1.22.6;docker pull --platform amd64 istio/proxyv2:1.22.6;docker images;docker save -o calico-images-3.27.3-amd64.tar.gz istio/proxyv2:1.22.6 docker.io/istio/pilot:1.22.6
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: calico-images-3.27.3-amd64.tar.gz
          tag_name: 1.1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
